### ISSUE TITLE
update to latest angular 1.x

### ISSUE THREAD

**Issue by xtreemrage** [caseyjhol/ng-bootstrap-select#1]
When I install this, it will search for a suitable version, I work atm on 1.5.6, can you update this?

**Comment by caseyjhol** [comment]
Can you elaborate on your problem?

**Comment by xtreemrage** [comment]
Sorry not really a problem, just a nice to have though. When I install this component with bower `bower install --save ng-bootstrap-select`, it will ask for a resolution. This component is looking for `angular v1.3.X`, but I'm already @ `v1.5.x`. And I need to add a `resolutions` object in my bower.json file, just for this component.

I need to add the resolution object, so when other team members are doing their `bower install` command, it will not interrupt (with a question) the installation process of the other components.
